version: '3.8'

services:
  coredns:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5983:5983/udp"
    volumes:
      - ./Corefile:/root/Corefile
    depends_on:
      - gameserver
    networks:
      - dnsgame-net

  gameserver:
    build:
      context: ./gameserver
    ports:
      - "8080:8080"
    networks:
      - dnsgame-net

  webinterface:
    build:
      context: ./webinterface
    ports:
      - "8081:8081"
    depends_on:
      - gameserver
    networks:
      - dnsgame-net

  stresstest:
    build:
      context: ./stresstest
    image: stresstest
    depends_on:
      - webinterface
      - gameserver
      - coredns
    environment:
      NUM_PLAYERS: 1000
      MAX_WORKERS: 150
      NUM_THREADS: 150
      DNS_SERVER: coredns
      DNS_PORT: 5983
      WEB_INTERFACE_HOST: webinterface:8081
      STARTUP_DELAY: 10
    networks:
      - dnsgame-net

networks:
  dnsgame-net:
    driver: bridge