version: '3.8'

services:
  coredns:
    build:
      context: ./dnsrp
    ports:
      - "5983:5983/udp"
    depends_on:
      - gameserver
    networks:
      - dnsgame-net

  gameserver:
    build:
      context: ./gameserver
    ports:
      - "8080:8080"
    volumes:
      - ./data:/litefs
    networks:
      - dnsgame-net

  webinterface:
    build:
      context: ./webinterface
    ports:
      - "8081:8081"
    depends_on:
      - gameserver
    networks:
      - dnsgame-net

#  stresstest:
#    build:
#      context: ./stresstest
#    image: stresstest
#    depends_on:
#      - webinterface
#      - gameserver
#      - coredns
#    environment:
#      NUM_PLAYERS: 50
#      MAX_WORKERS: 50
#      NUM_THREADS: 50
#      DNS_SERVER: coredns
#      DNS_PORT: 5983
#      WEB_INTERFACE_HOST: webinterface:8081
#      STARTUP_DELAY: 10
#    networks:
#      - dnsgame-net

  loader:
    build:
      context: ./loader
    depends_on:
      - gameserver
      - coredns
    environment:
      DNS_SERVER: coredns
      DNS_PORT: 5983
      METRICS_URL: http://gameserver:8080/metrics
      TARGET_QUEUE_SIZE: 100
      ADJUST_INTERVAL: 10s
      CHECK_INTERVAL: 5s
    networks:
      - dnsgame-net

networks:
  dnsgame-net:
    driver: bridge
